/*
 * generated by Xtext 2.11.0
 */
package org.uis.lenguajegrafico.ide


/**
 * Use this class to register ide components.
 */
class LenguajegraficoIdeModule extends AbstractLenguajegraficoIdeModule {
}
