/**
 * generated by Xtext 2.11.0
 */
package org.uis.lenguajegrafico.validation;

import org.uis.lenguajegrafico.validation.AbstractLenguajegraficoValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class LenguajegraficoValidator extends AbstractLenguajegraficoValidator {
}
