/*
 * generated by Xtext 2.13.0-SNAPSHOT
 */
package org.uis.lenguajegrafico.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.uis.lenguajegrafico.ui.internal.LenguajegraficoActivator;

public class LenguajegraficoUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return LenguajegraficoActivator.getInstance().getInjector("org.uis.lenguajegrafico.Lenguajegrafico");
	}

}
