/**
 * generated by Xtext 2.13.0-SNAPSHOT
 */
package org.uis.lenguajegrafico.lenguajegrafico;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Code Generated Target</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.uis.lenguajegrafico.lenguajegrafico.LenguajegraficoPackage#getCodeGeneratedTarget()
 * @model
 * @generated
 */
public interface CodeGeneratedTarget extends Configuration
{
} // CodeGeneratedTarget
