/**
 * generated by Xtext 2.13.0-SNAPSHOT
 */
package org.uis.lenguajegrafico.lenguajegrafico;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Float</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.uis.lenguajegrafico.lenguajegrafico.LenguajegraficoPackage#getFloat()
 * @model
 * @generated
 */
public interface Float extends Datatype
{
} // Float
