/**
 * generated by Xtext 2.13.0-SNAPSHOT
 */
package org.uis.lenguajegrafico.lenguajegrafico;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.uis.lenguajegrafico.lenguajegrafico.LenguajegraficoFactory
 * @model kind="package"
 * @generated
 */
public interface LenguajegraficoPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "lenguajegrafico";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.uis.org/lenguajegrafico/Lenguajegrafico";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "lenguajegrafico";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  LenguajegraficoPackage eINSTANCE = org.uis.lenguajegrafico.lenguajegrafico.impl.LenguajegraficoPackageImpl.init();

  /**
   * The meta object id for the '{@link org.uis.lenguajegrafico.lenguajegrafico.impl.LenguajegraficoImpl <em>Lenguajegrafico</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.uis.lenguajegrafico.lenguajegrafico.impl.LenguajegraficoImpl
   * @see org.uis.lenguajegrafico.lenguajegrafico.impl.LenguajegraficoPackageImpl#getLenguajegrafico()
   * @generated
   */
  int LENGUAJEGRAFICO = 0;

  /**
   * The feature id for the '<em><b>Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LENGUAJEGRAFICO__ELEMENTS = 0;

  /**
   * The number of structural features of the '<em>Lenguajegrafico</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LENGUAJEGRAFICO_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.uis.lenguajegrafico.lenguajegrafico.impl.ElementImpl <em>Element</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.uis.lenguajegrafico.lenguajegrafico.impl.ElementImpl
   * @see org.uis.lenguajegrafico.lenguajegrafico.impl.LenguajegraficoPackageImpl#getElement()
   * @generated
   */
  int ELEMENT = 1;

  /**
   * The number of structural features of the '<em>Element</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMENT_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.uis.lenguajegrafico.lenguajegrafico.impl.DatatypeImpl <em>Datatype</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.uis.lenguajegrafico.lenguajegrafico.impl.DatatypeImpl
   * @see org.uis.lenguajegrafico.lenguajegrafico.impl.LenguajegraficoPackageImpl#getDatatype()
   * @generated
   */
  int DATATYPE = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATATYPE__NAME = 0;

  /**
   * The number of structural features of the '<em>Datatype</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATATYPE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.uis.lenguajegrafico.lenguajegrafico.impl.ChartImpl <em>Chart</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.uis.lenguajegrafico.lenguajegrafico.impl.ChartImpl
   * @see org.uis.lenguajegrafico.lenguajegrafico.impl.LenguajegraficoPackageImpl#getChart()
   * @generated
   */
  int CHART = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHART__NAME = ELEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Features</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHART__FEATURES = ELEMENT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Chart</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHART_FEATURE_COUNT = ELEMENT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.uis.lenguajegrafico.lenguajegrafico.impl.TupleImpl <em>Tuple</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.uis.lenguajegrafico.lenguajegrafico.impl.TupleImpl
   * @see org.uis.lenguajegrafico.lenguajegrafico.impl.LenguajegraficoPackageImpl#getTuple()
   * @generated
   */
  int TUPLE = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TUPLE__NAME = ELEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Url</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TUPLE__URL = ELEMENT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Tuple</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TUPLE_FEATURE_COUNT = ELEMENT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.uis.lenguajegrafico.lenguajegrafico.impl.TextImpl <em>Text</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.uis.lenguajegrafico.lenguajegrafico.impl.TextImpl
   * @see org.uis.lenguajegrafico.lenguajegrafico.impl.LenguajegraficoPackageImpl#getText()
   * @generated
   */
  int TEXT = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEXT__NAME = DATATYPE__NAME;

  /**
   * The number of structural features of the '<em>Text</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEXT_FEATURE_COUNT = DATATYPE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.uis.lenguajegrafico.lenguajegrafico.impl.NumberImpl <em>Number</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.uis.lenguajegrafico.lenguajegrafico.impl.NumberImpl
   * @see org.uis.lenguajegrafico.lenguajegrafico.impl.LenguajegraficoPackageImpl#getNumber()
   * @generated
   */
  int NUMBER = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NUMBER__NAME = DATATYPE__NAME;

  /**
   * The number of structural features of the '<em>Number</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NUMBER_FEATURE_COUNT = DATATYPE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.uis.lenguajegrafico.lenguajegrafico.impl.FloatImpl <em>Float</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.uis.lenguajegrafico.lenguajegrafico.impl.FloatImpl
   * @see org.uis.lenguajegrafico.lenguajegrafico.impl.LenguajegraficoPackageImpl#getFloat()
   * @generated
   */
  int FLOAT = 7;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FLOAT__NAME = DATATYPE__NAME;

  /**
   * The number of structural features of the '<em>Float</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FLOAT_FEATURE_COUNT = DATATYPE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.uis.lenguajegrafico.lenguajegrafico.impl.URLImpl <em>URL</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.uis.lenguajegrafico.lenguajegrafico.impl.URLImpl
   * @see org.uis.lenguajegrafico.lenguajegrafico.impl.LenguajegraficoPackageImpl#getURL()
   * @generated
   */
  int URL = 8;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int URL__VALUE = 0;

  /**
   * The number of structural features of the '<em>URL</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int URL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.uis.lenguajegrafico.lenguajegrafico.impl.TitleImpl <em>Title</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.uis.lenguajegrafico.lenguajegrafico.impl.TitleImpl
   * @see org.uis.lenguajegrafico.lenguajegrafico.impl.LenguajegraficoPackageImpl#getTitle()
   * @generated
   */
  int TITLE = 9;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TITLE__VALUE = 0;

  /**
   * The number of structural features of the '<em>Title</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TITLE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.uis.lenguajegrafico.lenguajegrafico.impl.LabelxImpl <em>Labelx</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.uis.lenguajegrafico.lenguajegrafico.impl.LabelxImpl
   * @see org.uis.lenguajegrafico.lenguajegrafico.impl.LenguajegraficoPackageImpl#getLabelx()
   * @generated
   */
  int LABELX = 10;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LABELX__VALUE = 0;

  /**
   * The number of structural features of the '<em>Labelx</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LABELX_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.uis.lenguajegrafico.lenguajegrafico.impl.LabelyImpl <em>Labely</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.uis.lenguajegrafico.lenguajegrafico.impl.LabelyImpl
   * @see org.uis.lenguajegrafico.lenguajegrafico.impl.LenguajegraficoPackageImpl#getLabely()
   * @generated
   */
  int LABELY = 11;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LABELY__VALUE = 0;

  /**
   * The number of structural features of the '<em>Labely</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LABELY_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.uis.lenguajegrafico.lenguajegrafico.impl.LegendImpl <em>Legend</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.uis.lenguajegrafico.lenguajegrafico.impl.LegendImpl
   * @see org.uis.lenguajegrafico.lenguajegrafico.impl.LenguajegraficoPackageImpl#getLegend()
   * @generated
   */
  int LEGEND = 12;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LEGEND__VALUE = 0;

  /**
   * The number of structural features of the '<em>Legend</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LEGEND_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.uis.lenguajegrafico.lenguajegrafico.impl.HoleImpl <em>Hole</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.uis.lenguajegrafico.lenguajegrafico.impl.HoleImpl
   * @see org.uis.lenguajegrafico.lenguajegrafico.impl.LenguajegraficoPackageImpl#getHole()
   * @generated
   */
  int HOLE = 13;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HOLE__VALUE = 0;

  /**
   * The number of structural features of the '<em>Hole</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HOLE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.uis.lenguajegrafico.lenguajegrafico.impl.OrientationImpl <em>Orientation</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.uis.lenguajegrafico.lenguajegrafico.impl.OrientationImpl
   * @see org.uis.lenguajegrafico.lenguajegrafico.impl.LenguajegraficoPackageImpl#getOrientation()
   * @generated
   */
  int ORIENTATION = 14;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ORIENTATION__VALUE = 0;

  /**
   * The number of structural features of the '<em>Orientation</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ORIENTATION_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.uis.lenguajegrafico.lenguajegrafico.impl.AreaImpl <em>Area</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.uis.lenguajegrafico.lenguajegrafico.impl.AreaImpl
   * @see org.uis.lenguajegrafico.lenguajegrafico.impl.LenguajegraficoPackageImpl#getArea()
   * @generated
   */
  int AREA = 15;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AREA__VALUE = 0;

  /**
   * The number of structural features of the '<em>Area</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AREA_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.uis.lenguajegrafico.lenguajegrafico.impl.ZoomLevelImpl <em>Zoom Level</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.uis.lenguajegrafico.lenguajegrafico.impl.ZoomLevelImpl
   * @see org.uis.lenguajegrafico.lenguajegrafico.impl.LenguajegraficoPackageImpl#getZoomLevel()
   * @generated
   */
  int ZOOM_LEVEL = 16;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ZOOM_LEVEL__VALUE = 0;

  /**
   * The number of structural features of the '<em>Zoom Level</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ZOOM_LEVEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.uis.lenguajegrafico.lenguajegrafico.impl.MakerTypeImpl <em>Maker Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.uis.lenguajegrafico.lenguajegrafico.impl.MakerTypeImpl
   * @see org.uis.lenguajegrafico.lenguajegrafico.impl.LenguajegraficoPackageImpl#getMakerType()
   * @generated
   */
  int MAKER_TYPE = 17;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAKER_TYPE__VALUE = 0;

  /**
   * The number of structural features of the '<em>Maker Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAKER_TYPE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.uis.lenguajegrafico.lenguajegrafico.impl.MapTypeImpl <em>Map Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.uis.lenguajegrafico.lenguajegrafico.impl.MapTypeImpl
   * @see org.uis.lenguajegrafico.lenguajegrafico.impl.LenguajegraficoPackageImpl#getMapType()
   * @generated
   */
  int MAP_TYPE = 18;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAP_TYPE__VALUE = 0;

  /**
   * The number of structural features of the '<em>Map Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAP_TYPE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.uis.lenguajegrafico.lenguajegrafico.impl.CellSizeImpl <em>Cell Size</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.uis.lenguajegrafico.lenguajegrafico.impl.CellSizeImpl
   * @see org.uis.lenguajegrafico.lenguajegrafico.impl.LenguajegraficoPackageImpl#getCellSize()
   * @generated
   */
  int CELL_SIZE = 19;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CELL_SIZE__VALUE = 0;

  /**
   * The number of structural features of the '<em>Cell Size</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CELL_SIZE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.uis.lenguajegrafico.lenguajegrafico.impl.PieChartImpl <em>Pie Chart</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.uis.lenguajegrafico.lenguajegrafico.impl.PieChartImpl
   * @see org.uis.lenguajegrafico.lenguajegrafico.impl.LenguajegraficoPackageImpl#getPieChart()
   * @generated
   */
  int PIE_CHART = 20;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PIE_CHART__NAME = CHART__NAME;

  /**
   * The feature id for the '<em><b>Features</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PIE_CHART__FEATURES = CHART__FEATURES;

  /**
   * The feature id for the '<em><b>Tuple</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PIE_CHART__TUPLE = CHART_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Pie Chart</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PIE_CHART_FEATURE_COUNT = CHART_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.uis.lenguajegrafico.lenguajegrafico.impl.BarChartImpl <em>Bar Chart</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.uis.lenguajegrafico.lenguajegrafico.impl.BarChartImpl
   * @see org.uis.lenguajegrafico.lenguajegrafico.impl.LenguajegraficoPackageImpl#getBarChart()
   * @generated
   */
  int BAR_CHART = 21;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BAR_CHART__NAME = CHART__NAME;

  /**
   * The feature id for the '<em><b>Features</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BAR_CHART__FEATURES = CHART__FEATURES;

  /**
   * The feature id for the '<em><b>Tuple</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BAR_CHART__TUPLE = CHART_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Bar Chart</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BAR_CHART_FEATURE_COUNT = CHART_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.uis.lenguajegrafico.lenguajegrafico.impl.LineChartImpl <em>Line Chart</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.uis.lenguajegrafico.lenguajegrafico.impl.LineChartImpl
   * @see org.uis.lenguajegrafico.lenguajegrafico.impl.LenguajegraficoPackageImpl#getLineChart()
   * @generated
   */
  int LINE_CHART = 22;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LINE_CHART__NAME = CHART__NAME;

  /**
   * The feature id for the '<em><b>Features</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LINE_CHART__FEATURES = CHART__FEATURES;

  /**
   * The feature id for the '<em><b>Tuple</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LINE_CHART__TUPLE = CHART_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Line Chart</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LINE_CHART_FEATURE_COUNT = CHART_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.uis.lenguajegrafico.lenguajegrafico.impl.MapChartImpl <em>Map Chart</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.uis.lenguajegrafico.lenguajegrafico.impl.MapChartImpl
   * @see org.uis.lenguajegrafico.lenguajegrafico.impl.LenguajegraficoPackageImpl#getMapChart()
   * @generated
   */
  int MAP_CHART = 23;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAP_CHART__NAME = CHART__NAME;

  /**
   * The feature id for the '<em><b>Features</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAP_CHART__FEATURES = CHART__FEATURES;

  /**
   * The feature id for the '<em><b>Tuple</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAP_CHART__TUPLE = CHART_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Map Chart</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAP_CHART_FEATURE_COUNT = CHART_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.uis.lenguajegrafico.lenguajegrafico.impl.TableChartImpl <em>Table Chart</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.uis.lenguajegrafico.lenguajegrafico.impl.TableChartImpl
   * @see org.uis.lenguajegrafico.lenguajegrafico.impl.LenguajegraficoPackageImpl#getTableChart()
   * @generated
   */
  int TABLE_CHART = 24;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TABLE_CHART__NAME = CHART__NAME;

  /**
   * The feature id for the '<em><b>Features</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TABLE_CHART__FEATURES = CHART__FEATURES;

  /**
   * The feature id for the '<em><b>Tuple</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TABLE_CHART__TUPLE = CHART_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Table Chart</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TABLE_CHART_FEATURE_COUNT = CHART_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.uis.lenguajegrafico.lenguajegrafico.impl.DashBoardImpl <em>Dash Board</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.uis.lenguajegrafico.lenguajegrafico.impl.DashBoardImpl
   * @see org.uis.lenguajegrafico.lenguajegrafico.impl.LenguajegraficoPackageImpl#getDashBoard()
   * @generated
   */
  int DASH_BOARD = 25;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DASH_BOARD__NAME = ELEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Charts</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DASH_BOARD__CHARTS = ELEMENT_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Features</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DASH_BOARD__FEATURES = ELEMENT_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Dash Board</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DASH_BOARD_FEATURE_COUNT = ELEMENT_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link org.uis.lenguajegrafico.lenguajegrafico.impl.Tuple1Impl <em>Tuple1</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.uis.lenguajegrafico.lenguajegrafico.impl.Tuple1Impl
   * @see org.uis.lenguajegrafico.lenguajegrafico.impl.LenguajegraficoPackageImpl#getTuple1()
   * @generated
   */
  int TUPLE1 = 26;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TUPLE1__NAME = TUPLE__NAME;

  /**
   * The feature id for the '<em><b>Url</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TUPLE1__URL = TUPLE__URL;

  /**
   * The feature id for the '<em><b>Value1</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TUPLE1__VALUE1 = TUPLE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Value2</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TUPLE1__VALUE2 = TUPLE_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Tuple1</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TUPLE1_FEATURE_COUNT = TUPLE_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.uis.lenguajegrafico.lenguajegrafico.impl.Tuple2Impl <em>Tuple2</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.uis.lenguajegrafico.lenguajegrafico.impl.Tuple2Impl
   * @see org.uis.lenguajegrafico.lenguajegrafico.impl.LenguajegraficoPackageImpl#getTuple2()
   * @generated
   */
  int TUPLE2 = 27;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TUPLE2__NAME = TUPLE__NAME;

  /**
   * The feature id for the '<em><b>Url</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TUPLE2__URL = TUPLE__URL;

  /**
   * The feature id for the '<em><b>Value1</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TUPLE2__VALUE1 = TUPLE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Value2</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TUPLE2__VALUE2 = TUPLE_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Tuple2</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TUPLE2_FEATURE_COUNT = TUPLE_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.uis.lenguajegrafico.lenguajegrafico.impl.Tuple3Impl <em>Tuple3</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.uis.lenguajegrafico.lenguajegrafico.impl.Tuple3Impl
   * @see org.uis.lenguajegrafico.lenguajegrafico.impl.LenguajegraficoPackageImpl#getTuple3()
   * @generated
   */
  int TUPLE3 = 28;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TUPLE3__NAME = TUPLE__NAME;

  /**
   * The feature id for the '<em><b>Url</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TUPLE3__URL = TUPLE__URL;

  /**
   * The feature id for the '<em><b>Value1</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TUPLE3__VALUE1 = TUPLE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Value2</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TUPLE3__VALUE2 = TUPLE_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Value3</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TUPLE3__VALUE3 = TUPLE_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Tuple3</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TUPLE3_FEATURE_COUNT = TUPLE_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link org.uis.lenguajegrafico.lenguajegrafico.impl.Tuple4Impl <em>Tuple4</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.uis.lenguajegrafico.lenguajegrafico.impl.Tuple4Impl
   * @see org.uis.lenguajegrafico.lenguajegrafico.impl.LenguajegraficoPackageImpl#getTuple4()
   * @generated
   */
  int TUPLE4 = 29;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TUPLE4__NAME = TUPLE__NAME;

  /**
   * The feature id for the '<em><b>Url</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TUPLE4__URL = TUPLE__URL;

  /**
   * The feature id for the '<em><b>Values</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TUPLE4__VALUES = TUPLE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Tuple4</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TUPLE4_FEATURE_COUNT = TUPLE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.uis.lenguajegrafico.lenguajegrafico.impl.ConfigurationImpl <em>Configuration</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.uis.lenguajegrafico.lenguajegrafico.impl.ConfigurationImpl
   * @see org.uis.lenguajegrafico.lenguajegrafico.impl.LenguajegraficoPackageImpl#getConfiguration()
   * @generated
   */
  int CONFIGURATION = 30;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONFIGURATION__VALUE = ELEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Configuration</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONFIGURATION_FEATURE_COUNT = ELEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.uis.lenguajegrafico.lenguajegrafico.impl.CodeGeneratedTargetImpl <em>Code Generated Target</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.uis.lenguajegrafico.lenguajegrafico.impl.CodeGeneratedTargetImpl
   * @see org.uis.lenguajegrafico.lenguajegrafico.impl.LenguajegraficoPackageImpl#getCodeGeneratedTarget()
   * @generated
   */
  int CODE_GENERATED_TARGET = 31;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CODE_GENERATED_TARGET__VALUE = CONFIGURATION__VALUE;

  /**
   * The number of structural features of the '<em>Code Generated Target</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CODE_GENERATED_TARGET_FEATURE_COUNT = CONFIGURATION_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.uis.lenguajegrafico.lenguajegrafico.impl.NormaliceDataImpl <em>Normalice Data</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.uis.lenguajegrafico.lenguajegrafico.impl.NormaliceDataImpl
   * @see org.uis.lenguajegrafico.lenguajegrafico.impl.LenguajegraficoPackageImpl#getNormaliceData()
   * @generated
   */
  int NORMALICE_DATA = 32;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NORMALICE_DATA__VALUE = CONFIGURATION__VALUE;

  /**
   * The number of structural features of the '<em>Normalice Data</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NORMALICE_DATA_FEATURE_COUNT = CONFIGURATION_FEATURE_COUNT + 0;


  /**
   * Returns the meta object for class '{@link org.uis.lenguajegrafico.lenguajegrafico.Lenguajegrafico <em>Lenguajegrafico</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Lenguajegrafico</em>'.
   * @see org.uis.lenguajegrafico.lenguajegrafico.Lenguajegrafico
   * @generated
   */
  EClass getLenguajegrafico();

  /**
   * Returns the meta object for the containment reference list '{@link org.uis.lenguajegrafico.lenguajegrafico.Lenguajegrafico#getElements <em>Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Elements</em>'.
   * @see org.uis.lenguajegrafico.lenguajegrafico.Lenguajegrafico#getElements()
   * @see #getLenguajegrafico()
   * @generated
   */
  EReference getLenguajegrafico_Elements();

  /**
   * Returns the meta object for class '{@link org.uis.lenguajegrafico.lenguajegrafico.Element <em>Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Element</em>'.
   * @see org.uis.lenguajegrafico.lenguajegrafico.Element
   * @generated
   */
  EClass getElement();

  /**
   * Returns the meta object for class '{@link org.uis.lenguajegrafico.lenguajegrafico.Datatype <em>Datatype</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Datatype</em>'.
   * @see org.uis.lenguajegrafico.lenguajegrafico.Datatype
   * @generated
   */
  EClass getDatatype();

  /**
   * Returns the meta object for the attribute '{@link org.uis.lenguajegrafico.lenguajegrafico.Datatype#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.uis.lenguajegrafico.lenguajegrafico.Datatype#getName()
   * @see #getDatatype()
   * @generated
   */
  EAttribute getDatatype_Name();

  /**
   * Returns the meta object for class '{@link org.uis.lenguajegrafico.lenguajegrafico.Chart <em>Chart</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Chart</em>'.
   * @see org.uis.lenguajegrafico.lenguajegrafico.Chart
   * @generated
   */
  EClass getChart();

  /**
   * Returns the meta object for the attribute '{@link org.uis.lenguajegrafico.lenguajegrafico.Chart#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.uis.lenguajegrafico.lenguajegrafico.Chart#getName()
   * @see #getChart()
   * @generated
   */
  EAttribute getChart_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.uis.lenguajegrafico.lenguajegrafico.Chart#getFeatures <em>Features</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Features</em>'.
   * @see org.uis.lenguajegrafico.lenguajegrafico.Chart#getFeatures()
   * @see #getChart()
   * @generated
   */
  EReference getChart_Features();

  /**
   * Returns the meta object for class '{@link org.uis.lenguajegrafico.lenguajegrafico.Tuple <em>Tuple</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Tuple</em>'.
   * @see org.uis.lenguajegrafico.lenguajegrafico.Tuple
   * @generated
   */
  EClass getTuple();

  /**
   * Returns the meta object for the attribute '{@link org.uis.lenguajegrafico.lenguajegrafico.Tuple#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.uis.lenguajegrafico.lenguajegrafico.Tuple#getName()
   * @see #getTuple()
   * @generated
   */
  EAttribute getTuple_Name();

  /**
   * Returns the meta object for the containment reference '{@link org.uis.lenguajegrafico.lenguajegrafico.Tuple#getUrl <em>Url</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Url</em>'.
   * @see org.uis.lenguajegrafico.lenguajegrafico.Tuple#getUrl()
   * @see #getTuple()
   * @generated
   */
  EReference getTuple_Url();

  /**
   * Returns the meta object for class '{@link org.uis.lenguajegrafico.lenguajegrafico.Text <em>Text</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Text</em>'.
   * @see org.uis.lenguajegrafico.lenguajegrafico.Text
   * @generated
   */
  EClass getText();

  /**
   * Returns the meta object for class '{@link org.uis.lenguajegrafico.lenguajegrafico.Number <em>Number</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Number</em>'.
   * @see org.uis.lenguajegrafico.lenguajegrafico.Number
   * @generated
   */
  EClass getNumber();

  /**
   * Returns the meta object for class '{@link org.uis.lenguajegrafico.lenguajegrafico.Float <em>Float</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Float</em>'.
   * @see org.uis.lenguajegrafico.lenguajegrafico.Float
   * @generated
   */
  EClass getFloat();

  /**
   * Returns the meta object for class '{@link org.uis.lenguajegrafico.lenguajegrafico.URL <em>URL</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>URL</em>'.
   * @see org.uis.lenguajegrafico.lenguajegrafico.URL
   * @generated
   */
  EClass getURL();

  /**
   * Returns the meta object for the attribute '{@link org.uis.lenguajegrafico.lenguajegrafico.URL#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.uis.lenguajegrafico.lenguajegrafico.URL#getValue()
   * @see #getURL()
   * @generated
   */
  EAttribute getURL_Value();

  /**
   * Returns the meta object for class '{@link org.uis.lenguajegrafico.lenguajegrafico.Title <em>Title</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Title</em>'.
   * @see org.uis.lenguajegrafico.lenguajegrafico.Title
   * @generated
   */
  EClass getTitle();

  /**
   * Returns the meta object for the attribute '{@link org.uis.lenguajegrafico.lenguajegrafico.Title#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.uis.lenguajegrafico.lenguajegrafico.Title#getValue()
   * @see #getTitle()
   * @generated
   */
  EAttribute getTitle_Value();

  /**
   * Returns the meta object for class '{@link org.uis.lenguajegrafico.lenguajegrafico.Labelx <em>Labelx</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Labelx</em>'.
   * @see org.uis.lenguajegrafico.lenguajegrafico.Labelx
   * @generated
   */
  EClass getLabelx();

  /**
   * Returns the meta object for the attribute '{@link org.uis.lenguajegrafico.lenguajegrafico.Labelx#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.uis.lenguajegrafico.lenguajegrafico.Labelx#getValue()
   * @see #getLabelx()
   * @generated
   */
  EAttribute getLabelx_Value();

  /**
   * Returns the meta object for class '{@link org.uis.lenguajegrafico.lenguajegrafico.Labely <em>Labely</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Labely</em>'.
   * @see org.uis.lenguajegrafico.lenguajegrafico.Labely
   * @generated
   */
  EClass getLabely();

  /**
   * Returns the meta object for the attribute '{@link org.uis.lenguajegrafico.lenguajegrafico.Labely#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.uis.lenguajegrafico.lenguajegrafico.Labely#getValue()
   * @see #getLabely()
   * @generated
   */
  EAttribute getLabely_Value();

  /**
   * Returns the meta object for class '{@link org.uis.lenguajegrafico.lenguajegrafico.Legend <em>Legend</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Legend</em>'.
   * @see org.uis.lenguajegrafico.lenguajegrafico.Legend
   * @generated
   */
  EClass getLegend();

  /**
   * Returns the meta object for the attribute '{@link org.uis.lenguajegrafico.lenguajegrafico.Legend#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.uis.lenguajegrafico.lenguajegrafico.Legend#getValue()
   * @see #getLegend()
   * @generated
   */
  EAttribute getLegend_Value();

  /**
   * Returns the meta object for class '{@link org.uis.lenguajegrafico.lenguajegrafico.Hole <em>Hole</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Hole</em>'.
   * @see org.uis.lenguajegrafico.lenguajegrafico.Hole
   * @generated
   */
  EClass getHole();

  /**
   * Returns the meta object for the attribute '{@link org.uis.lenguajegrafico.lenguajegrafico.Hole#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.uis.lenguajegrafico.lenguajegrafico.Hole#getValue()
   * @see #getHole()
   * @generated
   */
  EAttribute getHole_Value();

  /**
   * Returns the meta object for class '{@link org.uis.lenguajegrafico.lenguajegrafico.Orientation <em>Orientation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Orientation</em>'.
   * @see org.uis.lenguajegrafico.lenguajegrafico.Orientation
   * @generated
   */
  EClass getOrientation();

  /**
   * Returns the meta object for the attribute '{@link org.uis.lenguajegrafico.lenguajegrafico.Orientation#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.uis.lenguajegrafico.lenguajegrafico.Orientation#getValue()
   * @see #getOrientation()
   * @generated
   */
  EAttribute getOrientation_Value();

  /**
   * Returns the meta object for class '{@link org.uis.lenguajegrafico.lenguajegrafico.Area <em>Area</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Area</em>'.
   * @see org.uis.lenguajegrafico.lenguajegrafico.Area
   * @generated
   */
  EClass getArea();

  /**
   * Returns the meta object for the attribute '{@link org.uis.lenguajegrafico.lenguajegrafico.Area#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.uis.lenguajegrafico.lenguajegrafico.Area#getValue()
   * @see #getArea()
   * @generated
   */
  EAttribute getArea_Value();

  /**
   * Returns the meta object for class '{@link org.uis.lenguajegrafico.lenguajegrafico.ZoomLevel <em>Zoom Level</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Zoom Level</em>'.
   * @see org.uis.lenguajegrafico.lenguajegrafico.ZoomLevel
   * @generated
   */
  EClass getZoomLevel();

  /**
   * Returns the meta object for the attribute '{@link org.uis.lenguajegrafico.lenguajegrafico.ZoomLevel#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.uis.lenguajegrafico.lenguajegrafico.ZoomLevel#getValue()
   * @see #getZoomLevel()
   * @generated
   */
  EAttribute getZoomLevel_Value();

  /**
   * Returns the meta object for class '{@link org.uis.lenguajegrafico.lenguajegrafico.MakerType <em>Maker Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Maker Type</em>'.
   * @see org.uis.lenguajegrafico.lenguajegrafico.MakerType
   * @generated
   */
  EClass getMakerType();

  /**
   * Returns the meta object for the attribute '{@link org.uis.lenguajegrafico.lenguajegrafico.MakerType#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.uis.lenguajegrafico.lenguajegrafico.MakerType#getValue()
   * @see #getMakerType()
   * @generated
   */
  EAttribute getMakerType_Value();

  /**
   * Returns the meta object for class '{@link org.uis.lenguajegrafico.lenguajegrafico.MapType <em>Map Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Map Type</em>'.
   * @see org.uis.lenguajegrafico.lenguajegrafico.MapType
   * @generated
   */
  EClass getMapType();

  /**
   * Returns the meta object for the attribute '{@link org.uis.lenguajegrafico.lenguajegrafico.MapType#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.uis.lenguajegrafico.lenguajegrafico.MapType#getValue()
   * @see #getMapType()
   * @generated
   */
  EAttribute getMapType_Value();

  /**
   * Returns the meta object for class '{@link org.uis.lenguajegrafico.lenguajegrafico.CellSize <em>Cell Size</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Cell Size</em>'.
   * @see org.uis.lenguajegrafico.lenguajegrafico.CellSize
   * @generated
   */
  EClass getCellSize();

  /**
   * Returns the meta object for the attribute '{@link org.uis.lenguajegrafico.lenguajegrafico.CellSize#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.uis.lenguajegrafico.lenguajegrafico.CellSize#getValue()
   * @see #getCellSize()
   * @generated
   */
  EAttribute getCellSize_Value();

  /**
   * Returns the meta object for class '{@link org.uis.lenguajegrafico.lenguajegrafico.PieChart <em>Pie Chart</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Pie Chart</em>'.
   * @see org.uis.lenguajegrafico.lenguajegrafico.PieChart
   * @generated
   */
  EClass getPieChart();

  /**
   * Returns the meta object for the reference '{@link org.uis.lenguajegrafico.lenguajegrafico.PieChart#getTuple <em>Tuple</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Tuple</em>'.
   * @see org.uis.lenguajegrafico.lenguajegrafico.PieChart#getTuple()
   * @see #getPieChart()
   * @generated
   */
  EReference getPieChart_Tuple();

  /**
   * Returns the meta object for class '{@link org.uis.lenguajegrafico.lenguajegrafico.BarChart <em>Bar Chart</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Bar Chart</em>'.
   * @see org.uis.lenguajegrafico.lenguajegrafico.BarChart
   * @generated
   */
  EClass getBarChart();

  /**
   * Returns the meta object for the reference '{@link org.uis.lenguajegrafico.lenguajegrafico.BarChart#getTuple <em>Tuple</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Tuple</em>'.
   * @see org.uis.lenguajegrafico.lenguajegrafico.BarChart#getTuple()
   * @see #getBarChart()
   * @generated
   */
  EReference getBarChart_Tuple();

  /**
   * Returns the meta object for class '{@link org.uis.lenguajegrafico.lenguajegrafico.LineChart <em>Line Chart</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Line Chart</em>'.
   * @see org.uis.lenguajegrafico.lenguajegrafico.LineChart
   * @generated
   */
  EClass getLineChart();

  /**
   * Returns the meta object for the reference '{@link org.uis.lenguajegrafico.lenguajegrafico.LineChart#getTuple <em>Tuple</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Tuple</em>'.
   * @see org.uis.lenguajegrafico.lenguajegrafico.LineChart#getTuple()
   * @see #getLineChart()
   * @generated
   */
  EReference getLineChart_Tuple();

  /**
   * Returns the meta object for class '{@link org.uis.lenguajegrafico.lenguajegrafico.MapChart <em>Map Chart</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Map Chart</em>'.
   * @see org.uis.lenguajegrafico.lenguajegrafico.MapChart
   * @generated
   */
  EClass getMapChart();

  /**
   * Returns the meta object for the reference '{@link org.uis.lenguajegrafico.lenguajegrafico.MapChart#getTuple <em>Tuple</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Tuple</em>'.
   * @see org.uis.lenguajegrafico.lenguajegrafico.MapChart#getTuple()
   * @see #getMapChart()
   * @generated
   */
  EReference getMapChart_Tuple();

  /**
   * Returns the meta object for class '{@link org.uis.lenguajegrafico.lenguajegrafico.TableChart <em>Table Chart</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Table Chart</em>'.
   * @see org.uis.lenguajegrafico.lenguajegrafico.TableChart
   * @generated
   */
  EClass getTableChart();

  /**
   * Returns the meta object for the reference '{@link org.uis.lenguajegrafico.lenguajegrafico.TableChart#getTuple <em>Tuple</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Tuple</em>'.
   * @see org.uis.lenguajegrafico.lenguajegrafico.TableChart#getTuple()
   * @see #getTableChart()
   * @generated
   */
  EReference getTableChart_Tuple();

  /**
   * Returns the meta object for class '{@link org.uis.lenguajegrafico.lenguajegrafico.DashBoard <em>Dash Board</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Dash Board</em>'.
   * @see org.uis.lenguajegrafico.lenguajegrafico.DashBoard
   * @generated
   */
  EClass getDashBoard();

  /**
   * Returns the meta object for the attribute '{@link org.uis.lenguajegrafico.lenguajegrafico.DashBoard#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.uis.lenguajegrafico.lenguajegrafico.DashBoard#getName()
   * @see #getDashBoard()
   * @generated
   */
  EAttribute getDashBoard_Name();

  /**
   * Returns the meta object for the reference list '{@link org.uis.lenguajegrafico.lenguajegrafico.DashBoard#getCharts <em>Charts</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Charts</em>'.
   * @see org.uis.lenguajegrafico.lenguajegrafico.DashBoard#getCharts()
   * @see #getDashBoard()
   * @generated
   */
  EReference getDashBoard_Charts();

  /**
   * Returns the meta object for the containment reference list '{@link org.uis.lenguajegrafico.lenguajegrafico.DashBoard#getFeatures <em>Features</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Features</em>'.
   * @see org.uis.lenguajegrafico.lenguajegrafico.DashBoard#getFeatures()
   * @see #getDashBoard()
   * @generated
   */
  EReference getDashBoard_Features();

  /**
   * Returns the meta object for class '{@link org.uis.lenguajegrafico.lenguajegrafico.Tuple1 <em>Tuple1</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Tuple1</em>'.
   * @see org.uis.lenguajegrafico.lenguajegrafico.Tuple1
   * @generated
   */
  EClass getTuple1();

  /**
   * Returns the meta object for the containment reference '{@link org.uis.lenguajegrafico.lenguajegrafico.Tuple1#getValue1 <em>Value1</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Value1</em>'.
   * @see org.uis.lenguajegrafico.lenguajegrafico.Tuple1#getValue1()
   * @see #getTuple1()
   * @generated
   */
  EReference getTuple1_Value1();

  /**
   * Returns the meta object for the containment reference '{@link org.uis.lenguajegrafico.lenguajegrafico.Tuple1#getValue2 <em>Value2</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Value2</em>'.
   * @see org.uis.lenguajegrafico.lenguajegrafico.Tuple1#getValue2()
   * @see #getTuple1()
   * @generated
   */
  EReference getTuple1_Value2();

  /**
   * Returns the meta object for class '{@link org.uis.lenguajegrafico.lenguajegrafico.Tuple2 <em>Tuple2</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Tuple2</em>'.
   * @see org.uis.lenguajegrafico.lenguajegrafico.Tuple2
   * @generated
   */
  EClass getTuple2();

  /**
   * Returns the meta object for the containment reference '{@link org.uis.lenguajegrafico.lenguajegrafico.Tuple2#getValue1 <em>Value1</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Value1</em>'.
   * @see org.uis.lenguajegrafico.lenguajegrafico.Tuple2#getValue1()
   * @see #getTuple2()
   * @generated
   */
  EReference getTuple2_Value1();

  /**
   * Returns the meta object for the containment reference list '{@link org.uis.lenguajegrafico.lenguajegrafico.Tuple2#getValue2 <em>Value2</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Value2</em>'.
   * @see org.uis.lenguajegrafico.lenguajegrafico.Tuple2#getValue2()
   * @see #getTuple2()
   * @generated
   */
  EReference getTuple2_Value2();

  /**
   * Returns the meta object for class '{@link org.uis.lenguajegrafico.lenguajegrafico.Tuple3 <em>Tuple3</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Tuple3</em>'.
   * @see org.uis.lenguajegrafico.lenguajegrafico.Tuple3
   * @generated
   */
  EClass getTuple3();

  /**
   * Returns the meta object for the containment reference '{@link org.uis.lenguajegrafico.lenguajegrafico.Tuple3#getValue1 <em>Value1</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Value1</em>'.
   * @see org.uis.lenguajegrafico.lenguajegrafico.Tuple3#getValue1()
   * @see #getTuple3()
   * @generated
   */
  EReference getTuple3_Value1();

  /**
   * Returns the meta object for the containment reference '{@link org.uis.lenguajegrafico.lenguajegrafico.Tuple3#getValue2 <em>Value2</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Value2</em>'.
   * @see org.uis.lenguajegrafico.lenguajegrafico.Tuple3#getValue2()
   * @see #getTuple3()
   * @generated
   */
  EReference getTuple3_Value2();

  /**
   * Returns the meta object for the containment reference '{@link org.uis.lenguajegrafico.lenguajegrafico.Tuple3#getValue3 <em>Value3</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Value3</em>'.
   * @see org.uis.lenguajegrafico.lenguajegrafico.Tuple3#getValue3()
   * @see #getTuple3()
   * @generated
   */
  EReference getTuple3_Value3();

  /**
   * Returns the meta object for class '{@link org.uis.lenguajegrafico.lenguajegrafico.Tuple4 <em>Tuple4</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Tuple4</em>'.
   * @see org.uis.lenguajegrafico.lenguajegrafico.Tuple4
   * @generated
   */
  EClass getTuple4();

  /**
   * Returns the meta object for the containment reference list '{@link org.uis.lenguajegrafico.lenguajegrafico.Tuple4#getValues <em>Values</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Values</em>'.
   * @see org.uis.lenguajegrafico.lenguajegrafico.Tuple4#getValues()
   * @see #getTuple4()
   * @generated
   */
  EReference getTuple4_Values();

  /**
   * Returns the meta object for class '{@link org.uis.lenguajegrafico.lenguajegrafico.Configuration <em>Configuration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Configuration</em>'.
   * @see org.uis.lenguajegrafico.lenguajegrafico.Configuration
   * @generated
   */
  EClass getConfiguration();

  /**
   * Returns the meta object for the attribute '{@link org.uis.lenguajegrafico.lenguajegrafico.Configuration#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.uis.lenguajegrafico.lenguajegrafico.Configuration#getValue()
   * @see #getConfiguration()
   * @generated
   */
  EAttribute getConfiguration_Value();

  /**
   * Returns the meta object for class '{@link org.uis.lenguajegrafico.lenguajegrafico.CodeGeneratedTarget <em>Code Generated Target</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Code Generated Target</em>'.
   * @see org.uis.lenguajegrafico.lenguajegrafico.CodeGeneratedTarget
   * @generated
   */
  EClass getCodeGeneratedTarget();

  /**
   * Returns the meta object for class '{@link org.uis.lenguajegrafico.lenguajegrafico.NormaliceData <em>Normalice Data</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Normalice Data</em>'.
   * @see org.uis.lenguajegrafico.lenguajegrafico.NormaliceData
   * @generated
   */
  EClass getNormaliceData();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  LenguajegraficoFactory getLenguajegraficoFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.uis.lenguajegrafico.lenguajegrafico.impl.LenguajegraficoImpl <em>Lenguajegrafico</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.uis.lenguajegrafico.lenguajegrafico.impl.LenguajegraficoImpl
     * @see org.uis.lenguajegrafico.lenguajegrafico.impl.LenguajegraficoPackageImpl#getLenguajegrafico()
     * @generated
     */
    EClass LENGUAJEGRAFICO = eINSTANCE.getLenguajegrafico();

    /**
     * The meta object literal for the '<em><b>Elements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LENGUAJEGRAFICO__ELEMENTS = eINSTANCE.getLenguajegrafico_Elements();

    /**
     * The meta object literal for the '{@link org.uis.lenguajegrafico.lenguajegrafico.impl.ElementImpl <em>Element</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.uis.lenguajegrafico.lenguajegrafico.impl.ElementImpl
     * @see org.uis.lenguajegrafico.lenguajegrafico.impl.LenguajegraficoPackageImpl#getElement()
     * @generated
     */
    EClass ELEMENT = eINSTANCE.getElement();

    /**
     * The meta object literal for the '{@link org.uis.lenguajegrafico.lenguajegrafico.impl.DatatypeImpl <em>Datatype</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.uis.lenguajegrafico.lenguajegrafico.impl.DatatypeImpl
     * @see org.uis.lenguajegrafico.lenguajegrafico.impl.LenguajegraficoPackageImpl#getDatatype()
     * @generated
     */
    EClass DATATYPE = eINSTANCE.getDatatype();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DATATYPE__NAME = eINSTANCE.getDatatype_Name();

    /**
     * The meta object literal for the '{@link org.uis.lenguajegrafico.lenguajegrafico.impl.ChartImpl <em>Chart</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.uis.lenguajegrafico.lenguajegrafico.impl.ChartImpl
     * @see org.uis.lenguajegrafico.lenguajegrafico.impl.LenguajegraficoPackageImpl#getChart()
     * @generated
     */
    EClass CHART = eINSTANCE.getChart();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CHART__NAME = eINSTANCE.getChart_Name();

    /**
     * The meta object literal for the '<em><b>Features</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CHART__FEATURES = eINSTANCE.getChart_Features();

    /**
     * The meta object literal for the '{@link org.uis.lenguajegrafico.lenguajegrafico.impl.TupleImpl <em>Tuple</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.uis.lenguajegrafico.lenguajegrafico.impl.TupleImpl
     * @see org.uis.lenguajegrafico.lenguajegrafico.impl.LenguajegraficoPackageImpl#getTuple()
     * @generated
     */
    EClass TUPLE = eINSTANCE.getTuple();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TUPLE__NAME = eINSTANCE.getTuple_Name();

    /**
     * The meta object literal for the '<em><b>Url</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TUPLE__URL = eINSTANCE.getTuple_Url();

    /**
     * The meta object literal for the '{@link org.uis.lenguajegrafico.lenguajegrafico.impl.TextImpl <em>Text</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.uis.lenguajegrafico.lenguajegrafico.impl.TextImpl
     * @see org.uis.lenguajegrafico.lenguajegrafico.impl.LenguajegraficoPackageImpl#getText()
     * @generated
     */
    EClass TEXT = eINSTANCE.getText();

    /**
     * The meta object literal for the '{@link org.uis.lenguajegrafico.lenguajegrafico.impl.NumberImpl <em>Number</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.uis.lenguajegrafico.lenguajegrafico.impl.NumberImpl
     * @see org.uis.lenguajegrafico.lenguajegrafico.impl.LenguajegraficoPackageImpl#getNumber()
     * @generated
     */
    EClass NUMBER = eINSTANCE.getNumber();

    /**
     * The meta object literal for the '{@link org.uis.lenguajegrafico.lenguajegrafico.impl.FloatImpl <em>Float</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.uis.lenguajegrafico.lenguajegrafico.impl.FloatImpl
     * @see org.uis.lenguajegrafico.lenguajegrafico.impl.LenguajegraficoPackageImpl#getFloat()
     * @generated
     */
    EClass FLOAT = eINSTANCE.getFloat();

    /**
     * The meta object literal for the '{@link org.uis.lenguajegrafico.lenguajegrafico.impl.URLImpl <em>URL</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.uis.lenguajegrafico.lenguajegrafico.impl.URLImpl
     * @see org.uis.lenguajegrafico.lenguajegrafico.impl.LenguajegraficoPackageImpl#getURL()
     * @generated
     */
    EClass URL = eINSTANCE.getURL();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute URL__VALUE = eINSTANCE.getURL_Value();

    /**
     * The meta object literal for the '{@link org.uis.lenguajegrafico.lenguajegrafico.impl.TitleImpl <em>Title</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.uis.lenguajegrafico.lenguajegrafico.impl.TitleImpl
     * @see org.uis.lenguajegrafico.lenguajegrafico.impl.LenguajegraficoPackageImpl#getTitle()
     * @generated
     */
    EClass TITLE = eINSTANCE.getTitle();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TITLE__VALUE = eINSTANCE.getTitle_Value();

    /**
     * The meta object literal for the '{@link org.uis.lenguajegrafico.lenguajegrafico.impl.LabelxImpl <em>Labelx</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.uis.lenguajegrafico.lenguajegrafico.impl.LabelxImpl
     * @see org.uis.lenguajegrafico.lenguajegrafico.impl.LenguajegraficoPackageImpl#getLabelx()
     * @generated
     */
    EClass LABELX = eINSTANCE.getLabelx();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LABELX__VALUE = eINSTANCE.getLabelx_Value();

    /**
     * The meta object literal for the '{@link org.uis.lenguajegrafico.lenguajegrafico.impl.LabelyImpl <em>Labely</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.uis.lenguajegrafico.lenguajegrafico.impl.LabelyImpl
     * @see org.uis.lenguajegrafico.lenguajegrafico.impl.LenguajegraficoPackageImpl#getLabely()
     * @generated
     */
    EClass LABELY = eINSTANCE.getLabely();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LABELY__VALUE = eINSTANCE.getLabely_Value();

    /**
     * The meta object literal for the '{@link org.uis.lenguajegrafico.lenguajegrafico.impl.LegendImpl <em>Legend</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.uis.lenguajegrafico.lenguajegrafico.impl.LegendImpl
     * @see org.uis.lenguajegrafico.lenguajegrafico.impl.LenguajegraficoPackageImpl#getLegend()
     * @generated
     */
    EClass LEGEND = eINSTANCE.getLegend();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LEGEND__VALUE = eINSTANCE.getLegend_Value();

    /**
     * The meta object literal for the '{@link org.uis.lenguajegrafico.lenguajegrafico.impl.HoleImpl <em>Hole</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.uis.lenguajegrafico.lenguajegrafico.impl.HoleImpl
     * @see org.uis.lenguajegrafico.lenguajegrafico.impl.LenguajegraficoPackageImpl#getHole()
     * @generated
     */
    EClass HOLE = eINSTANCE.getHole();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute HOLE__VALUE = eINSTANCE.getHole_Value();

    /**
     * The meta object literal for the '{@link org.uis.lenguajegrafico.lenguajegrafico.impl.OrientationImpl <em>Orientation</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.uis.lenguajegrafico.lenguajegrafico.impl.OrientationImpl
     * @see org.uis.lenguajegrafico.lenguajegrafico.impl.LenguajegraficoPackageImpl#getOrientation()
     * @generated
     */
    EClass ORIENTATION = eINSTANCE.getOrientation();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ORIENTATION__VALUE = eINSTANCE.getOrientation_Value();

    /**
     * The meta object literal for the '{@link org.uis.lenguajegrafico.lenguajegrafico.impl.AreaImpl <em>Area</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.uis.lenguajegrafico.lenguajegrafico.impl.AreaImpl
     * @see org.uis.lenguajegrafico.lenguajegrafico.impl.LenguajegraficoPackageImpl#getArea()
     * @generated
     */
    EClass AREA = eINSTANCE.getArea();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute AREA__VALUE = eINSTANCE.getArea_Value();

    /**
     * The meta object literal for the '{@link org.uis.lenguajegrafico.lenguajegrafico.impl.ZoomLevelImpl <em>Zoom Level</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.uis.lenguajegrafico.lenguajegrafico.impl.ZoomLevelImpl
     * @see org.uis.lenguajegrafico.lenguajegrafico.impl.LenguajegraficoPackageImpl#getZoomLevel()
     * @generated
     */
    EClass ZOOM_LEVEL = eINSTANCE.getZoomLevel();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ZOOM_LEVEL__VALUE = eINSTANCE.getZoomLevel_Value();

    /**
     * The meta object literal for the '{@link org.uis.lenguajegrafico.lenguajegrafico.impl.MakerTypeImpl <em>Maker Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.uis.lenguajegrafico.lenguajegrafico.impl.MakerTypeImpl
     * @see org.uis.lenguajegrafico.lenguajegrafico.impl.LenguajegraficoPackageImpl#getMakerType()
     * @generated
     */
    EClass MAKER_TYPE = eINSTANCE.getMakerType();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MAKER_TYPE__VALUE = eINSTANCE.getMakerType_Value();

    /**
     * The meta object literal for the '{@link org.uis.lenguajegrafico.lenguajegrafico.impl.MapTypeImpl <em>Map Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.uis.lenguajegrafico.lenguajegrafico.impl.MapTypeImpl
     * @see org.uis.lenguajegrafico.lenguajegrafico.impl.LenguajegraficoPackageImpl#getMapType()
     * @generated
     */
    EClass MAP_TYPE = eINSTANCE.getMapType();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MAP_TYPE__VALUE = eINSTANCE.getMapType_Value();

    /**
     * The meta object literal for the '{@link org.uis.lenguajegrafico.lenguajegrafico.impl.CellSizeImpl <em>Cell Size</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.uis.lenguajegrafico.lenguajegrafico.impl.CellSizeImpl
     * @see org.uis.lenguajegrafico.lenguajegrafico.impl.LenguajegraficoPackageImpl#getCellSize()
     * @generated
     */
    EClass CELL_SIZE = eINSTANCE.getCellSize();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CELL_SIZE__VALUE = eINSTANCE.getCellSize_Value();

    /**
     * The meta object literal for the '{@link org.uis.lenguajegrafico.lenguajegrafico.impl.PieChartImpl <em>Pie Chart</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.uis.lenguajegrafico.lenguajegrafico.impl.PieChartImpl
     * @see org.uis.lenguajegrafico.lenguajegrafico.impl.LenguajegraficoPackageImpl#getPieChart()
     * @generated
     */
    EClass PIE_CHART = eINSTANCE.getPieChart();

    /**
     * The meta object literal for the '<em><b>Tuple</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PIE_CHART__TUPLE = eINSTANCE.getPieChart_Tuple();

    /**
     * The meta object literal for the '{@link org.uis.lenguajegrafico.lenguajegrafico.impl.BarChartImpl <em>Bar Chart</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.uis.lenguajegrafico.lenguajegrafico.impl.BarChartImpl
     * @see org.uis.lenguajegrafico.lenguajegrafico.impl.LenguajegraficoPackageImpl#getBarChart()
     * @generated
     */
    EClass BAR_CHART = eINSTANCE.getBarChart();

    /**
     * The meta object literal for the '<em><b>Tuple</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BAR_CHART__TUPLE = eINSTANCE.getBarChart_Tuple();

    /**
     * The meta object literal for the '{@link org.uis.lenguajegrafico.lenguajegrafico.impl.LineChartImpl <em>Line Chart</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.uis.lenguajegrafico.lenguajegrafico.impl.LineChartImpl
     * @see org.uis.lenguajegrafico.lenguajegrafico.impl.LenguajegraficoPackageImpl#getLineChart()
     * @generated
     */
    EClass LINE_CHART = eINSTANCE.getLineChart();

    /**
     * The meta object literal for the '<em><b>Tuple</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LINE_CHART__TUPLE = eINSTANCE.getLineChart_Tuple();

    /**
     * The meta object literal for the '{@link org.uis.lenguajegrafico.lenguajegrafico.impl.MapChartImpl <em>Map Chart</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.uis.lenguajegrafico.lenguajegrafico.impl.MapChartImpl
     * @see org.uis.lenguajegrafico.lenguajegrafico.impl.LenguajegraficoPackageImpl#getMapChart()
     * @generated
     */
    EClass MAP_CHART = eINSTANCE.getMapChart();

    /**
     * The meta object literal for the '<em><b>Tuple</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MAP_CHART__TUPLE = eINSTANCE.getMapChart_Tuple();

    /**
     * The meta object literal for the '{@link org.uis.lenguajegrafico.lenguajegrafico.impl.TableChartImpl <em>Table Chart</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.uis.lenguajegrafico.lenguajegrafico.impl.TableChartImpl
     * @see org.uis.lenguajegrafico.lenguajegrafico.impl.LenguajegraficoPackageImpl#getTableChart()
     * @generated
     */
    EClass TABLE_CHART = eINSTANCE.getTableChart();

    /**
     * The meta object literal for the '<em><b>Tuple</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TABLE_CHART__TUPLE = eINSTANCE.getTableChart_Tuple();

    /**
     * The meta object literal for the '{@link org.uis.lenguajegrafico.lenguajegrafico.impl.DashBoardImpl <em>Dash Board</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.uis.lenguajegrafico.lenguajegrafico.impl.DashBoardImpl
     * @see org.uis.lenguajegrafico.lenguajegrafico.impl.LenguajegraficoPackageImpl#getDashBoard()
     * @generated
     */
    EClass DASH_BOARD = eINSTANCE.getDashBoard();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DASH_BOARD__NAME = eINSTANCE.getDashBoard_Name();

    /**
     * The meta object literal for the '<em><b>Charts</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DASH_BOARD__CHARTS = eINSTANCE.getDashBoard_Charts();

    /**
     * The meta object literal for the '<em><b>Features</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DASH_BOARD__FEATURES = eINSTANCE.getDashBoard_Features();

    /**
     * The meta object literal for the '{@link org.uis.lenguajegrafico.lenguajegrafico.impl.Tuple1Impl <em>Tuple1</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.uis.lenguajegrafico.lenguajegrafico.impl.Tuple1Impl
     * @see org.uis.lenguajegrafico.lenguajegrafico.impl.LenguajegraficoPackageImpl#getTuple1()
     * @generated
     */
    EClass TUPLE1 = eINSTANCE.getTuple1();

    /**
     * The meta object literal for the '<em><b>Value1</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TUPLE1__VALUE1 = eINSTANCE.getTuple1_Value1();

    /**
     * The meta object literal for the '<em><b>Value2</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TUPLE1__VALUE2 = eINSTANCE.getTuple1_Value2();

    /**
     * The meta object literal for the '{@link org.uis.lenguajegrafico.lenguajegrafico.impl.Tuple2Impl <em>Tuple2</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.uis.lenguajegrafico.lenguajegrafico.impl.Tuple2Impl
     * @see org.uis.lenguajegrafico.lenguajegrafico.impl.LenguajegraficoPackageImpl#getTuple2()
     * @generated
     */
    EClass TUPLE2 = eINSTANCE.getTuple2();

    /**
     * The meta object literal for the '<em><b>Value1</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TUPLE2__VALUE1 = eINSTANCE.getTuple2_Value1();

    /**
     * The meta object literal for the '<em><b>Value2</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TUPLE2__VALUE2 = eINSTANCE.getTuple2_Value2();

    /**
     * The meta object literal for the '{@link org.uis.lenguajegrafico.lenguajegrafico.impl.Tuple3Impl <em>Tuple3</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.uis.lenguajegrafico.lenguajegrafico.impl.Tuple3Impl
     * @see org.uis.lenguajegrafico.lenguajegrafico.impl.LenguajegraficoPackageImpl#getTuple3()
     * @generated
     */
    EClass TUPLE3 = eINSTANCE.getTuple3();

    /**
     * The meta object literal for the '<em><b>Value1</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TUPLE3__VALUE1 = eINSTANCE.getTuple3_Value1();

    /**
     * The meta object literal for the '<em><b>Value2</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TUPLE3__VALUE2 = eINSTANCE.getTuple3_Value2();

    /**
     * The meta object literal for the '<em><b>Value3</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TUPLE3__VALUE3 = eINSTANCE.getTuple3_Value3();

    /**
     * The meta object literal for the '{@link org.uis.lenguajegrafico.lenguajegrafico.impl.Tuple4Impl <em>Tuple4</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.uis.lenguajegrafico.lenguajegrafico.impl.Tuple4Impl
     * @see org.uis.lenguajegrafico.lenguajegrafico.impl.LenguajegraficoPackageImpl#getTuple4()
     * @generated
     */
    EClass TUPLE4 = eINSTANCE.getTuple4();

    /**
     * The meta object literal for the '<em><b>Values</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TUPLE4__VALUES = eINSTANCE.getTuple4_Values();

    /**
     * The meta object literal for the '{@link org.uis.lenguajegrafico.lenguajegrafico.impl.ConfigurationImpl <em>Configuration</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.uis.lenguajegrafico.lenguajegrafico.impl.ConfigurationImpl
     * @see org.uis.lenguajegrafico.lenguajegrafico.impl.LenguajegraficoPackageImpl#getConfiguration()
     * @generated
     */
    EClass CONFIGURATION = eINSTANCE.getConfiguration();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONFIGURATION__VALUE = eINSTANCE.getConfiguration_Value();

    /**
     * The meta object literal for the '{@link org.uis.lenguajegrafico.lenguajegrafico.impl.CodeGeneratedTargetImpl <em>Code Generated Target</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.uis.lenguajegrafico.lenguajegrafico.impl.CodeGeneratedTargetImpl
     * @see org.uis.lenguajegrafico.lenguajegrafico.impl.LenguajegraficoPackageImpl#getCodeGeneratedTarget()
     * @generated
     */
    EClass CODE_GENERATED_TARGET = eINSTANCE.getCodeGeneratedTarget();

    /**
     * The meta object literal for the '{@link org.uis.lenguajegrafico.lenguajegrafico.impl.NormaliceDataImpl <em>Normalice Data</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.uis.lenguajegrafico.lenguajegrafico.impl.NormaliceDataImpl
     * @see org.uis.lenguajegrafico.lenguajegrafico.impl.LenguajegraficoPackageImpl#getNormaliceData()
     * @generated
     */
    EClass NORMALICE_DATA = eINSTANCE.getNormaliceData();

  }

} //LenguajegraficoPackage
