/**
 * generated by Xtext 2.13.0-SNAPSHOT
 */
package org.uis.lenguajegrafico.lenguajegrafico;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see org.uis.lenguajegrafico.lenguajegrafico.LenguajegraficoPackage
 * @generated
 */
public interface LenguajegraficoFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  LenguajegraficoFactory eINSTANCE = org.uis.lenguajegrafico.lenguajegrafico.impl.LenguajegraficoFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Lenguajegrafico</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Lenguajegrafico</em>'.
   * @generated
   */
  Lenguajegrafico createLenguajegrafico();

  /**
   * Returns a new object of class '<em>Element</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Element</em>'.
   * @generated
   */
  Element createElement();

  /**
   * Returns a new object of class '<em>Datatype</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Datatype</em>'.
   * @generated
   */
  Datatype createDatatype();

  /**
   * Returns a new object of class '<em>Chart</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Chart</em>'.
   * @generated
   */
  Chart createChart();

  /**
   * Returns a new object of class '<em>Tuple</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Tuple</em>'.
   * @generated
   */
  Tuple createTuple();

  /**
   * Returns a new object of class '<em>Text</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Text</em>'.
   * @generated
   */
  Text createText();

  /**
   * Returns a new object of class '<em>Number</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Number</em>'.
   * @generated
   */
  Number createNumber();

  /**
   * Returns a new object of class '<em>Float</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Float</em>'.
   * @generated
   */
  Float createFloat();

  /**
   * Returns a new object of class '<em>URL</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>URL</em>'.
   * @generated
   */
  URL createURL();

  /**
   * Returns a new object of class '<em>Title</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Title</em>'.
   * @generated
   */
  Title createTitle();

  /**
   * Returns a new object of class '<em>Labelx</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Labelx</em>'.
   * @generated
   */
  Labelx createLabelx();

  /**
   * Returns a new object of class '<em>Labely</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Labely</em>'.
   * @generated
   */
  Labely createLabely();

  /**
   * Returns a new object of class '<em>Legend</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Legend</em>'.
   * @generated
   */
  Legend createLegend();

  /**
   * Returns a new object of class '<em>Hole</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Hole</em>'.
   * @generated
   */
  Hole createHole();

  /**
   * Returns a new object of class '<em>Orientation</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Orientation</em>'.
   * @generated
   */
  Orientation createOrientation();

  /**
   * Returns a new object of class '<em>Area</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Area</em>'.
   * @generated
   */
  Area createArea();

  /**
   * Returns a new object of class '<em>Zoom Level</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Zoom Level</em>'.
   * @generated
   */
  ZoomLevel createZoomLevel();

  /**
   * Returns a new object of class '<em>Maker Type</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Maker Type</em>'.
   * @generated
   */
  MakerType createMakerType();

  /**
   * Returns a new object of class '<em>Map Type</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Map Type</em>'.
   * @generated
   */
  MapType createMapType();

  /**
   * Returns a new object of class '<em>Cell Size</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Cell Size</em>'.
   * @generated
   */
  CellSize createCellSize();

  /**
   * Returns a new object of class '<em>Pie Chart</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Pie Chart</em>'.
   * @generated
   */
  PieChart createPieChart();

  /**
   * Returns a new object of class '<em>Bar Chart</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Bar Chart</em>'.
   * @generated
   */
  BarChart createBarChart();

  /**
   * Returns a new object of class '<em>Line Chart</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Line Chart</em>'.
   * @generated
   */
  LineChart createLineChart();

  /**
   * Returns a new object of class '<em>Map Chart</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Map Chart</em>'.
   * @generated
   */
  MapChart createMapChart();

  /**
   * Returns a new object of class '<em>Table Chart</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Table Chart</em>'.
   * @generated
   */
  TableChart createTableChart();

  /**
   * Returns a new object of class '<em>Dash Board</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Dash Board</em>'.
   * @generated
   */
  DashBoard createDashBoard();

  /**
   * Returns a new object of class '<em>Tuple1</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Tuple1</em>'.
   * @generated
   */
  Tuple1 createTuple1();

  /**
   * Returns a new object of class '<em>Tuple2</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Tuple2</em>'.
   * @generated
   */
  Tuple2 createTuple2();

  /**
   * Returns a new object of class '<em>Tuple3</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Tuple3</em>'.
   * @generated
   */
  Tuple3 createTuple3();

  /**
   * Returns a new object of class '<em>Tuple4</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Tuple4</em>'.
   * @generated
   */
  Tuple4 createTuple4();

  /**
   * Returns a new object of class '<em>Configuration</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Configuration</em>'.
   * @generated
   */
  Configuration createConfiguration();

  /**
   * Returns a new object of class '<em>Code Generated Target</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Code Generated Target</em>'.
   * @generated
   */
  CodeGeneratedTarget createCodeGeneratedTarget();

  /**
   * Returns a new object of class '<em>Normalice Data</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Normalice Data</em>'.
   * @generated
   */
  NormaliceData createNormaliceData();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  LenguajegraficoPackage getLenguajegraficoPackage();

} //LenguajegraficoFactory
