/**
 * generated by Xtext 2.13.0-SNAPSHOT
 */
package org.uis.lenguajegrafico.lenguajegrafico;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Text</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.uis.lenguajegrafico.lenguajegrafico.LenguajegraficoPackage#getText()
 * @model
 * @generated
 */
public interface Text extends Datatype
{
} // Text
