/**
 * generated by Xtext 2.13.0-SNAPSHOT
 */
package org.uis.lenguajegrafico.lenguajegrafico;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Tuple2</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.uis.lenguajegrafico.lenguajegrafico.Tuple2#getValue1 <em>Value1</em>}</li>
 *   <li>{@link org.uis.lenguajegrafico.lenguajegrafico.Tuple2#getValue2 <em>Value2</em>}</li>
 * </ul>
 *
 * @see org.uis.lenguajegrafico.lenguajegrafico.LenguajegraficoPackage#getTuple2()
 * @model
 * @generated
 */
public interface Tuple2 extends Tuple
{
  /**
   * Returns the value of the '<em><b>Value1</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Value1</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value1</em>' containment reference.
   * @see #setValue1(Datatype)
   * @see org.uis.lenguajegrafico.lenguajegrafico.LenguajegraficoPackage#getTuple2_Value1()
   * @model containment="true"
   * @generated
   */
  Datatype getValue1();

  /**
   * Sets the value of the '{@link org.uis.lenguajegrafico.lenguajegrafico.Tuple2#getValue1 <em>Value1</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value1</em>' containment reference.
   * @see #getValue1()
   * @generated
   */
  void setValue1(Datatype value);

  /**
   * Returns the value of the '<em><b>Value2</b></em>' containment reference list.
   * The list contents are of type {@link org.uis.lenguajegrafico.lenguajegrafico.Number}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Value2</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value2</em>' containment reference list.
   * @see org.uis.lenguajegrafico.lenguajegrafico.LenguajegraficoPackage#getTuple2_Value2()
   * @model containment="true"
   * @generated
   */
  EList<org.uis.lenguajegrafico.lenguajegrafico.Number> getValue2();

} // Tuple2
