/**
 * generated by Xtext 2.13.0-SNAPSHOT
 */
package org.uis.lenguajegrafico.lenguajegrafico;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Tuple1</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.uis.lenguajegrafico.lenguajegrafico.Tuple1#getValue1 <em>Value1</em>}</li>
 *   <li>{@link org.uis.lenguajegrafico.lenguajegrafico.Tuple1#getValue2 <em>Value2</em>}</li>
 * </ul>
 *
 * @see org.uis.lenguajegrafico.lenguajegrafico.LenguajegraficoPackage#getTuple1()
 * @model
 * @generated
 */
public interface Tuple1 extends Tuple
{
  /**
   * Returns the value of the '<em><b>Value1</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Value1</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value1</em>' containment reference.
   * @see #setValue1(Text)
   * @see org.uis.lenguajegrafico.lenguajegrafico.LenguajegraficoPackage#getTuple1_Value1()
   * @model containment="true"
   * @generated
   */
  Text getValue1();

  /**
   * Sets the value of the '{@link org.uis.lenguajegrafico.lenguajegrafico.Tuple1#getValue1 <em>Value1</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value1</em>' containment reference.
   * @see #getValue1()
   * @generated
   */
  void setValue1(Text value);

  /**
   * Returns the value of the '<em><b>Value2</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Value2</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value2</em>' containment reference.
   * @see #setValue2(org.uis.lenguajegrafico.lenguajegrafico.Number)
   * @see org.uis.lenguajegrafico.lenguajegrafico.LenguajegraficoPackage#getTuple1_Value2()
   * @model containment="true"
   * @generated
   */
  org.uis.lenguajegrafico.lenguajegrafico.Number getValue2();

  /**
   * Sets the value of the '{@link org.uis.lenguajegrafico.lenguajegrafico.Tuple1#getValue2 <em>Value2</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value2</em>' containment reference.
   * @see #getValue2()
   * @generated
   */
  void setValue2(org.uis.lenguajegrafico.lenguajegrafico.Number value);

} // Tuple1
