/**
 * generated by Xtext 2.11.0
 */
package org.uis.lenguajegrafico.ui.contentassist;

import org.uis.lenguajegrafico.ui.contentassist.AbstractLenguajegraficoProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class LenguajegraficoProposalProvider extends AbstractLenguajegraficoProposalProvider {
}
