/**
 * generated by Xtext 2.13.0-SNAPSHOT
 */
package org.uis.lenguajegrafico.lenguajegrafico.impl;

import org.eclipse.emf.ecore.EClass;

import org.uis.lenguajegrafico.lenguajegrafico.CodeGeneratedTarget;
import org.uis.lenguajegrafico.lenguajegrafico.LenguajegraficoPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Code Generated Target</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class CodeGeneratedTargetImpl extends ConfigurationImpl implements CodeGeneratedTarget
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected CodeGeneratedTargetImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return LenguajegraficoPackage.Literals.CODE_GENERATED_TARGET;
  }

} //CodeGeneratedTargetImpl
