/**
 * generated by Xtext 2.13.0-SNAPSHOT
 */
package org.uis.lenguajegrafico.lenguajegrafico.impl;

import org.eclipse.emf.ecore.EClass;

import org.uis.lenguajegrafico.lenguajegrafico.LenguajegraficoPackage;
import org.uis.lenguajegrafico.lenguajegrafico.NormaliceData;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Normalice Data</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class NormaliceDataImpl extends ConfigurationImpl implements NormaliceData
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected NormaliceDataImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return LenguajegraficoPackage.Literals.NORMALICE_DATA;
  }

} //NormaliceDataImpl
