/**
 * generated by Xtext 2.13.0-SNAPSHOT
 */
package org.uis.lenguajegrafico.lenguajegrafico.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.uis.lenguajegrafico.lenguajegrafico.Datatype;
import org.uis.lenguajegrafico.lenguajegrafico.LenguajegraficoPackage;
import org.uis.lenguajegrafico.lenguajegrafico.Tuple3;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Tuple3</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.uis.lenguajegrafico.lenguajegrafico.impl.Tuple3Impl#getValue1 <em>Value1</em>}</li>
 *   <li>{@link org.uis.lenguajegrafico.lenguajegrafico.impl.Tuple3Impl#getValue2 <em>Value2</em>}</li>
 *   <li>{@link org.uis.lenguajegrafico.lenguajegrafico.impl.Tuple3Impl#getValue3 <em>Value3</em>}</li>
 * </ul>
 *
 * @generated
 */
public class Tuple3Impl extends TupleImpl implements Tuple3
{
  /**
   * The cached value of the '{@link #getValue1() <em>Value1</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getValue1()
   * @generated
   * @ordered
   */
  protected org.uis.lenguajegrafico.lenguajegrafico.Float value1;

  /**
   * The cached value of the '{@link #getValue2() <em>Value2</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getValue2()
   * @generated
   * @ordered
   */
  protected org.uis.lenguajegrafico.lenguajegrafico.Float value2;

  /**
   * The cached value of the '{@link #getValue3() <em>Value3</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getValue3()
   * @generated
   * @ordered
   */
  protected Datatype value3;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected Tuple3Impl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return LenguajegraficoPackage.Literals.TUPLE3;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public org.uis.lenguajegrafico.lenguajegrafico.Float getValue1()
  {
    return value1;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetValue1(org.uis.lenguajegrafico.lenguajegrafico.Float newValue1, NotificationChain msgs)
  {
    org.uis.lenguajegrafico.lenguajegrafico.Float oldValue1 = value1;
    value1 = newValue1;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, LenguajegraficoPackage.TUPLE3__VALUE1, oldValue1, newValue1);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setValue1(org.uis.lenguajegrafico.lenguajegrafico.Float newValue1)
  {
    if (newValue1 != value1)
    {
      NotificationChain msgs = null;
      if (value1 != null)
        msgs = ((InternalEObject)value1).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - LenguajegraficoPackage.TUPLE3__VALUE1, null, msgs);
      if (newValue1 != null)
        msgs = ((InternalEObject)newValue1).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - LenguajegraficoPackage.TUPLE3__VALUE1, null, msgs);
      msgs = basicSetValue1(newValue1, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, LenguajegraficoPackage.TUPLE3__VALUE1, newValue1, newValue1));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public org.uis.lenguajegrafico.lenguajegrafico.Float getValue2()
  {
    return value2;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetValue2(org.uis.lenguajegrafico.lenguajegrafico.Float newValue2, NotificationChain msgs)
  {
    org.uis.lenguajegrafico.lenguajegrafico.Float oldValue2 = value2;
    value2 = newValue2;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, LenguajegraficoPackage.TUPLE3__VALUE2, oldValue2, newValue2);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setValue2(org.uis.lenguajegrafico.lenguajegrafico.Float newValue2)
  {
    if (newValue2 != value2)
    {
      NotificationChain msgs = null;
      if (value2 != null)
        msgs = ((InternalEObject)value2).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - LenguajegraficoPackage.TUPLE3__VALUE2, null, msgs);
      if (newValue2 != null)
        msgs = ((InternalEObject)newValue2).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - LenguajegraficoPackage.TUPLE3__VALUE2, null, msgs);
      msgs = basicSetValue2(newValue2, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, LenguajegraficoPackage.TUPLE3__VALUE2, newValue2, newValue2));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Datatype getValue3()
  {
    return value3;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetValue3(Datatype newValue3, NotificationChain msgs)
  {
    Datatype oldValue3 = value3;
    value3 = newValue3;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, LenguajegraficoPackage.TUPLE3__VALUE3, oldValue3, newValue3);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setValue3(Datatype newValue3)
  {
    if (newValue3 != value3)
    {
      NotificationChain msgs = null;
      if (value3 != null)
        msgs = ((InternalEObject)value3).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - LenguajegraficoPackage.TUPLE3__VALUE3, null, msgs);
      if (newValue3 != null)
        msgs = ((InternalEObject)newValue3).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - LenguajegraficoPackage.TUPLE3__VALUE3, null, msgs);
      msgs = basicSetValue3(newValue3, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, LenguajegraficoPackage.TUPLE3__VALUE3, newValue3, newValue3));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case LenguajegraficoPackage.TUPLE3__VALUE1:
        return basicSetValue1(null, msgs);
      case LenguajegraficoPackage.TUPLE3__VALUE2:
        return basicSetValue2(null, msgs);
      case LenguajegraficoPackage.TUPLE3__VALUE3:
        return basicSetValue3(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case LenguajegraficoPackage.TUPLE3__VALUE1:
        return getValue1();
      case LenguajegraficoPackage.TUPLE3__VALUE2:
        return getValue2();
      case LenguajegraficoPackage.TUPLE3__VALUE3:
        return getValue3();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case LenguajegraficoPackage.TUPLE3__VALUE1:
        setValue1((org.uis.lenguajegrafico.lenguajegrafico.Float)newValue);
        return;
      case LenguajegraficoPackage.TUPLE3__VALUE2:
        setValue2((org.uis.lenguajegrafico.lenguajegrafico.Float)newValue);
        return;
      case LenguajegraficoPackage.TUPLE3__VALUE3:
        setValue3((Datatype)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case LenguajegraficoPackage.TUPLE3__VALUE1:
        setValue1((org.uis.lenguajegrafico.lenguajegrafico.Float)null);
        return;
      case LenguajegraficoPackage.TUPLE3__VALUE2:
        setValue2((org.uis.lenguajegrafico.lenguajegrafico.Float)null);
        return;
      case LenguajegraficoPackage.TUPLE3__VALUE3:
        setValue3((Datatype)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case LenguajegraficoPackage.TUPLE3__VALUE1:
        return value1 != null;
      case LenguajegraficoPackage.TUPLE3__VALUE2:
        return value2 != null;
      case LenguajegraficoPackage.TUPLE3__VALUE3:
        return value3 != null;
    }
    return super.eIsSet(featureID);
  }

} //Tuple3Impl
