/**
 * generated by Xtext 2.11.0
 */
package org.uis.lenguajegrafico;

import org.uis.lenguajegrafico.LenguajegraficoStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class LenguajegraficoStandaloneSetup extends LenguajegraficoStandaloneSetupGenerated {
  public static void doSetup() {
    new LenguajegraficoStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
