/**
 * generated by Xtext 2.11.0
 */
package org.uis.lenguajegrafico;

import org.uis.lenguajegrafico.AbstractLenguajegraficoRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class LenguajegraficoRuntimeModule extends AbstractLenguajegraficoRuntimeModule {
}
